// Mocks generated by Mockito 5.4.6 from annotations
// in movie/test/presentation/provider/movie_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/core.dart' as _i6;
import 'package:core/data/services/watchlist_service.dart' as _i10;
import 'package:core/domain/entities/movie.dart' as _i9;
import 'package:core/domain/entities/movie_detail.dart' as _i7;
import 'package:core/domain/repositories/movie_repository.dart' as _i2;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/domain/usecases/get_movie_detail.dart' as _i4;
import 'package:movie/domain/usecases/get_movie_recommendations.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i4.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetail>>.value(
                  _FakeEither_1<_i6.Failure, _i7.MovieDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i8.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Movie>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i9.Movie>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i9.Movie>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i9.Movie>>>);
}

/// A class which mocks [WatchlistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistService extends _i1.Mock implements _i10.WatchlistService {
  MockWatchlistService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> addMovieWatchlist(
    _i7.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMovieWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#addMovieWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> removeMovieWatchlist(
    _i7.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeMovieWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#removeMovieWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> addTvSeriesWatchlist(
    _i6.TVSeriesDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTvSeriesWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#addTvSeriesWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> removeTvSeriesWatchlist(
    _i6.TVSeriesDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvSeriesWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#removeTvSeriesWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> loadTvSeriesWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadTvSeriesWatchlistStatus, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
