// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:core/data/services/watchlist_service.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/usecases/get_recommendations_tv_series.dart'
    as _i3;
import 'package:tv_series/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:tv_series/presentation/bloc/tv_series_detail_bloc.dart' as _i6;
import 'package:tv_series/presentation/bloc/tv_series_detail_event.dart' as _i8;
import 'package:tv_series/presentation/bloc/tv_series_detail_state.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetRecommendationsTVSeries_1 extends _i1.SmartFake
    implements _i3.GetRecommendationsTVSeries {
  _FakeGetRecommendationsTVSeries_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistService_2 extends _i1.SmartFake
    implements _i4.WatchlistService {
  _FakeWatchlistService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesDetailState_3 extends _i1.SmartFake
    implements _i5.TVSeriesDetailState {
  _FakeTVSeriesDetailState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailBloc extends _i1.Mock
    implements _i6.TVSeriesDetailBloc {
  MockTVSeriesDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesDetail),
            returnValue: _FakeGetTVSeriesDetail_0(
              this,
              Invocation.getter(#getTVSeriesDetail),
            ),
          )
          as _i2.GetTVSeriesDetail);

  @override
  _i3.GetRecommendationsTVSeries get getRecommendationsTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getRecommendationsTVSeries),
            returnValue: _FakeGetRecommendationsTVSeries_1(
              this,
              Invocation.getter(#getRecommendationsTVSeries),
            ),
          )
          as _i3.GetRecommendationsTVSeries);

  @override
  _i4.WatchlistService get watchlistService =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistService),
            returnValue: _FakeWatchlistService_2(
              this,
              Invocation.getter(#watchlistService),
            ),
          )
          as _i4.WatchlistService);

  @override
  _i5.TVSeriesDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTVSeriesDetailState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.TVSeriesDetailState);

  @override
  _i7.Stream<_i5.TVSeriesDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.TVSeriesDetailState>.empty(),
          )
          as _i7.Stream<_i5.TVSeriesDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i8.TVSeriesDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.TVSeriesDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.TVSeriesDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.TVSeriesDetailEvent>(
    _i9.EventHandler<E, _i5.TVSeriesDetailState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i8.TVSeriesDetailEvent, _i5.TVSeriesDetailState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i8.TVSeriesDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i5.TVSeriesDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
