// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/presentation/bloc/tv_series_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/core.dart' as _i2;
import 'package:core/data/services/watchlist_service.dart' as _i7;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/usecases/get_recommendations_tv_series.dart'
    as _i6;
import 'package:tv_series/domain/usecases/get_tv_series_detail.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTVSeriesRepository_0 extends _i1.SmartFake
    implements _i2.TVSeriesRepository {
  _FakeTVSeriesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTVSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVSeriesDetail extends _i1.Mock implements _i4.GetTVSeriesDetail {
  MockGetTVSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i5.Future<_i3.Either<_i2.Failure, _i2.TVSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i2.Failure, _i2.TVSeriesDetail>>.value(
                  _FakeEither_1<_i2.Failure, _i2.TVSeriesDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, _i2.TVSeriesDetail>>);
}

/// A class which mocks [GetRecommendationsTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendationsTVSeries extends _i1.Mock
    implements _i6.GetRecommendationsTVSeries {
  MockGetRecommendationsTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i5.Future<_i3.Either<_i2.Failure, List<_i2.TVSeries>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i3.Either<_i2.Failure, List<_i2.TVSeries>>>.value(
                  _FakeEither_1<_i2.Failure, List<_i2.TVSeries>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, List<_i2.TVSeries>>>);
}

/// A class which mocks [WatchlistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistService extends _i1.Mock implements _i7.WatchlistService {
  MockWatchlistService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> addMovieWatchlist(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMovieWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
              _FakeEither_1<_i2.Failure, String>(
                this,
                Invocation.method(#addMovieWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> removeMovieWatchlist(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeMovieWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
              _FakeEither_1<_i2.Failure, String>(
                this,
                Invocation.method(#removeMovieWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, String>>);

  @override
  _i5.Future<bool> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> addTvSeriesWatchlist(
    _i2.TVSeriesDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTvSeriesWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
              _FakeEither_1<_i2.Failure, String>(
                this,
                Invocation.method(#addTvSeriesWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i2.Failure, String>> removeTvSeriesWatchlist(
    _i2.TVSeriesDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvSeriesWatchlist, [movie]),
            returnValue: _i5.Future<_i3.Either<_i2.Failure, String>>.value(
              _FakeEither_1<_i2.Failure, String>(
                this,
                Invocation.method(#removeTvSeriesWatchlist, [movie]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i2.Failure, String>>);

  @override
  _i5.Future<bool> loadTvSeriesWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadTvSeriesWatchlistStatus, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
