// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/presentation/provider/watchlist_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/core.dart' as _i6;
import 'package:core/domain/entities/movie.dart' as _i7;
import 'package:core/domain/entities/tv_series.dart' as _i9;
import 'package:core/domain/repositories/tv_series_repository.dart' as _i3;
import 'package:core/domain/usecases/get_watchlist_movies.dart' as _i4;
import 'package:core/domain/usecases/get_watchlist_tv_series.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesRepository_1 extends _i1.SmartFake
    implements _i3.TVSeriesRepository {
  _FakeTVSeriesRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i4.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [GetWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTVSeries extends _i1.Mock
    implements _i8.GetWatchlistTVSeries {
  MockGetWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i9.TVSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i9.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i9.TVSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i9.TVSeries>>>);
}
